export interface Member {
  name: string;
  designation: string;
  batch: string;
  email: string;
  linkedin: string;
  image: string;
  isLead: boolean;
}

export const members: Member[] = [
  {
    name: "Abrar Azmain",
    designation: "Project Lead",
    batch: "ME-22",
    email: "rashidofficial5896@gmail.com",
    linkedin: "https://www.linkedin.com/in/rashid-abrar-azmain-csca™-b03683347",
    image: "/images/crew/Abrar Azmain.png",
    isLead: true,
  },
  {
    name: "Tamal Kaushik Barua",
    designation: "Design Team Lead",
    batch: "ME-22",
    email: "",
    linkedin: "http://www.linkedin.com/in/kaushik-barua755",
    image: "/images/crew/Tamal Kausik Barua.png",
    isLead: true,
  },
  {
    name: "Zabirul Islam Nabil",
    designation: "Design Team Lead",
    batch: "ME-22",
    email: "islamzabirul68@gmail.com",
    linkedin: "https://www.linkedin.com/in/zabirul-islam-06a5482b1",
    image: "/images/crew/Zabirul Islam Nabil.png",
    isLead: true,
  },
  {
    name: "Joy Sarkar",
    designation: "Design Team",
    batch: "ME-23",
    email: "sarkarjoy186@gmail.com",
    linkedin: "https://www.linkedin.com/in/joy-sarkar-674234276",
    image: "/images/crew/Joy Sarkar.png",
    isLead: false,
  },
  {
    name: "Mrenmoy Kumar Datta",
    designation: "Design Team",
    batch: "ME-23",
    email: "mrenmoy11034@gmail.com",
    linkedin: "https://www.linkedin.com/in/mrenmoy-kumar-datta-967b512",
    image: "/images/crew/Mrenmoy Kumar Datta.png",
    isLead: false,
  },
  {
    name: "Aninda Chowdhury",
    designation: "Design Team",
    batch: "ME-23",
    email: "aaninda009@gmail.com",
    linkedin: "https://www.linkedin.com/in/anindachowdhury009/",
    image: "/images/crew/Aninda Chowdhury.png",
    isLead: false,
  },
  {
    name: "Priyanti Biswas",
    designation: "Design Team",
    batch: "ME-23",
    email: "priyantikhushi13@gmail.com",
    linkedin: "https://www.linkedin.com/in/priyanti-biswas-1b6688355/",
    image: "/images/crew/Priyanti Biswas.png",
    isLead: false,
  },
  {
    name: "Mainul Islam",
    designation: "Simulation Team Lead",
    batch: "ME-22",
    email: "u2203071@student.cuet.ac.bd",
    linkedin: "https://www.linkedin.com/in/mainul-islam-5797013b3/",
    image: "/images/crew/Mainul Islam.png",
    isLead: true,
  },
  {
    name: "Khan Md. Nasif Hossain",
    designation: "Simulation Team Lead",
    batch: "ME-22",
    email: "nasifhossain07@gmail.com",
    linkedin: "https://www.linkedin.com/in/khan-md-nasif-hossain-9208453a0/",
    image: "/images/crew/Khan Md. Nasif Hossain.png",
    isLead: true,
  },
  {
    name: "Bijoy Barua",
    designation: "Simulation Team",
    batch: "ME-23",
    email: "baruabijoy369@gmail.com",
    linkedin: "https://www.linkedin.com/in/bijoybarua/",
    image: "/images/crew/Bijoy Barua.png",
    isLead: false,
  },
  {
    name: "Md. Mahtab Ahmed",
    designation: "Simulation Team",
    batch: "ME-23",
    email: "mahtabahmed0182@gmail.com",
    linkedin: "https://www.linkedin.com/in/mahtab-ahmed-876659352",
    image: "/images/crew/Md.Mahtab Ahmed.png",
    isLead: false,
  },
  {
    name: "Mehrab Waliullah",
    designation: "Branding & Communication Team Lead",
    batch: "ME-22",
    email: "mehrabmaher34@gmail.com",
    linkedin: "https://www.linkedin.com/in/mehrab-waliullah-maher-2a8818223/",
    image: "/images/crew/Mehrab Waliullah.png",
    isLead: true,
  },
  {
    name: "Miftahul Jannat Tanha",
    designation: "Branding & Communication Team",
    batch: "ME-23",
    email: "mjtanhachy@gmail.com",
    linkedin: "https://www.linkedin.com/in/miftahul-jannat-tanha/",
    image: "/images/crew/Miftahul Jannat Tanha.png",
    isLead: false,
  },
  {
    name: "Aiman Afia",
    designation: "Branding & Communication Team",
    batch: "ME-23",
    email: "afia0630ha@gmail.com",
    linkedin: "https://www.linkedin.com/in/aiman-afia-65475b367",
    image: "/images/crew/Aiman Afia.png",
    isLead: false,
  },
  {
    name: "Ayman Kalam",
    designation: "Branding & Communication Team",
    batch: "ME-23",
    email: "aymankalam06@gmail.com",
    linkedin: "https://www.linkedin.com/in/ayman-kalam-206172203",
    image: "/images/crew/Ayman Kalam.png",
    isLead: false,
  },
  {
    name: "Ayman Rafi",
    designation: "Research Team Lead",
    batch: "ME-22",
    email: "aymanrafi0418@gmail.com",
    linkedin: "https://www.linkedin.com/in/ayman-rafi-647708302",
    image: "/images/crew/Ayman Rafi.png",
    isLead: true,
  },
  {
    name: "Kazi Miftahul Hoque",
    designation: "Research Team",
    batch: "ME-23",
    email: "k.miftu.h@gmail.com",
    linkedin: "https://www.linkedin.com/in/kazi-miftahul-hoque",
    image: "/images/crew/Kazi Miftahul Hoque.png",
    isLead: false,
  },
  {
    name: "Tahmidul Abrar",
    designation: "Software Team Lead",
    batch: "ME-22",
    email: "tahmid.a158@gmail.com",
    linkedin: "https://www.linkedin.com/in/tahmid-ul-abrar-9999a1282/",
    image: "/images/crew/Tahmidul Abrar.png",
    isLead: true,
  },
  {
    name: "Mofasser Hossain Chowdhury",
    designation: "Software Team",
    batch: "ME-23",
    email: "mofasserchowdhury@gmail.com",
    linkedin: "https://www.linkedin.com/in/mofasser-hossain-chowdhury-75218121b/",
    image: "/images/crew/Mofasser Hossain Chowdhury.png",
    isLead: false,
  },
  {
    name: "Radia Zaman",
    designation: "Documentation Team Lead",
    batch: "ME-22",
    email: "",
    linkedin: "https://www.linkedin.com/in/radia-zaman-a867aa2b6/",
    image: "/images/crew/Radia Zaman.png",
    isLead: true,
  },
];
